[package]
name = "capsicum"
version = "0.1.0"
authors = ["Daniel Robertson <dan.robertson@anidata.org>"]
license = "MPL-2.0"
repository = "https://github.com/danlrobertson/capsicum-rs"
description = """
Simple intuitive Rust bindings for the FreeBSD capsicum library
"""
build = "build.rs"
